# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ff1be036fa3928ec5e6b379218da6a71e1deb8b6337634b75eeb83c265857e41d8d2662d85a9e9b00ad86f016f2e7f3ad5aaf6cab7d7614648f514a24cdd603

test:
  secret_key_base: 90cd36fe58762a896fa9128e54efc7b6432b0d5c45a8516b98e9496bbe311e1ae9ea0dde609962955a47df6b9a7b9ed8667c3a28a78ba3bc15bb8f7230c42793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
